FROM alpine:3.17

# Enable the community repository
RUN setup-apkrepos -c -1

# Install Tailscale
RUN apk update && apk add tailscale

# Run Tailscale in userspace networking mode
CMD ["tailscaled", "--state=/var/lib/tailscale/tailscaled.state", "--tun=userspace-networking"]
